function random() {
  const rand = Math.floor( Math.random() * 52) ; 
    if (rand == 0) msg = "松葉浴場";
    if (rand == 1) msg = "野天湯元・湯快爽快・くりひら";
    if (rand == 2) msg = "乙女湯";
    if (rand == 3) msg = "吉の湯";
    if (rand == 4) msg = "日の出おふろセンター";
    if (rand == 5) msg = "かまぶろ温泉";
    if (rand == 6) msg = "栄湯";
    if (rand == 7) msg = "政の湯";
    if (rand == 8) msg = "吉の湯";
    if (rand == 9) msg = "梅の湯";
    if (rand == 10) msg = "江川湯";
    if (rand == 11) msg = "山陽館";
    if (rand == 12) msg = "辰巳湯";
    if (rand == 13) msg = "小松湯";
    if (rand == 14) msg = "美和乃湯";
    if (rand == 15) msg = "平和湯";
    if (rand == 16) msg = "辰巳湯";
    if (rand == 17) msg = "小松湯";
    if (rand == 18) msg = "美和乃湯";
    if (rand == 19) msg = "平和湯";
    if (rand == 20) msg = "中島湯";
    if (rand == 21) msg = "星乃湯";
    if (rand == 22) msg = "寿恵弘湯（すえひろ湯）";
    if (rand == 23) msg = "浅田湯";
    if (rand == 24) msg = "有馬療養温泉旅館";
    if (rand == 25) msg = "宮前平源泉　湯けむりの庄";
    if (rand == 26) msg = "今井湯";
    if (rand == 27) msg = "橘湯";
    if (rand == 28) msg = "天神湯";
    if (rand == 29) msg = "丸子温泉";
    if (rand == 30) msg = "第一天神湯";
    if (rand == 31) msg = "里の湯";
    if (rand == 32) msg = "桐の湯";
    if (rand == 33) msg = "御幸湯";
    if (rand == 34) msg = "越の湯";
    if (rand == 35) msg = "睦湯";
    if (rand == 36) msg = "平和温泉";
    if (rand == 37) msg = "小倉湯";
    if (rand == 38) msg = "多賀良湯";
    if (rand == 39) msg = "富士見湯";
    if (rand == 40) msg = "縄文天然温泉　志楽の湯";
    if (rand == 41) msg = "たちばな温泉たちばな湯";
    if (rand == 42) msg = "バーデンプレイス";
    if (rand == 43) msg = "司湯";
    if (rand == 44) msg = "千歳温泉（千年湯）";
    if (rand == 45) msg = "鈴の湯";
    if (rand == 46) msg = "松の湯";
    if (rand == 47) msg = "高津湯";
    if (rand == 48) msg = "溝の口温泉　喜楽里";
    if (rand == 49) msg = "生田浴場";
    if (rand == 50) msg = "よしの湯";
    if (rand == 51) msg = "宿河原浴場";
  document.getElementById("kyoufuro").innerHTML = msg; 
  }